### ISSUE TITLE
百度网盘预训练模型的提取码是多少呢？

### ISSUE THREAD

**Issue by CachCheng** [jizhishutong/YOLOU#11]

**Comment by jizhishutong** [comment]
YOLO
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年7月29日 12:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [jizhishutong/YOLOU] 百度网盘预训练模型的提取码是多少呢？ (Issue #11) |

Closed #11 as completed.
