### ISSUE TITLE
yolov6 and yolox

### ISSUE THREAD

**Issue by Mobu59** [jizhishutong/YOLOU#18]
When will other pretrained models for yolox and other yaml profiles for yolov6 be released

**Comment by jizhishutong** [comment]
Sorry, this may take a while.

**Comment by Mobu59** [comment]
can you give the yaml of yolov6_tiny and yolov6-nano ,thanks a lot@jizhishutong

**Comment by jizhishutong** [comment]
coming soon!


---- Replied Message ----
| From | ***@***.***> |
| Date | 8/3/2022 16:45 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jizhishutong/YOLOU] yolov6 and yolox (Issue #18) |

can you give the yaml of yolov6_tiny and yolov6-nano ,thanks a ***@***.***

**Comment by Mobu59** [comment]
> can you give the yaml of yolov6_tiny and yolov6-nano ,thanks a lot@jizhishutong

solved
