### ISSUE TITLE
Question about pretrain weights

### ISSUE THREAD

**Issue by Mobu59** [jizhishutong/YOLOU#6]
Can the pre-trained model released by the official repository be used normally in this repository?

**Comment by jizhishutong** [comment]
no
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/28/2022 11:15 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [jizhishutong/YOLOU] Question about pretrain weights (Issue #6) |

Can the pre-trained model released by the official repository be used normally in this repository?
